"""empty message

Revision ID: 54be16465607
Revises: 
Create Date: 2019-02-01 13:57:37.782087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54be16465607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('subtitle', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=25), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('subs',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subs')
    op.drop_table('tags')
    op.drop_table('post')
    # ### end Alembic commands ###
